# Usa la imagen oficial de Python como base
FROM python:3.8-slim

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia el archivo de requerimientos
COPY airflow_mlflow/mlflow/1/6e395194149a4d79b260907d26a6527f/artifacts/DiabetesLogisticRegressionModel/model.pkl /app
COPY . /app

# Instala las dependencias
RUN pip install -r requirements.txt

# Expone el puerto 8501
EXPOSE 8501

# Comando para ejecutar la aplicación de Streamlit
CMD ["streamlit", "run", "interfaz.py"]
