# Usa la imagen oficial de Python como base
FROM python:3.8-slim

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia el archivo de requerimientos
OPY . /app

# Instala las dependencias
RUN pip install -r requirements.txt

# Expone el puerto 8501
EXPOSE 8501

# Comando para ejecutar la aplicación de Streamlit
CMD ["streamlit", "run", "interfaz.py"]
